config/routes.rb
::Refinery::Application.routes.draw do
  resources :orders, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    
    resources :orders do   
      match "update_awaiting_eft" => "orders#update_awaiting_eft", :as => "update_awaiting_eft"
      match "update_awaiting_cc" => "orders#update_awaiting_cc", :as => "update_awaiting_cc"
      match "update_new" => "orders#update_new", :as => "update_new"
      match "update_processing" => "orders#update_processing", :as => "update_processing"
      match "update_complete" => "orders#update_complete", :as => "update_complete"
      match "update_cancelled" => "orders#update_cancelled", :as => "update_cancelled"
      match "update_stale" => "orders#update_stale", :as => "update_stale"
      collection do
        get :notification_recipients
        post :notification_recipients
        
        post :update_positions         
        
      end
    end
  end
  
  resources :order_items, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :order_items, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  
  after_create :generate_reference_number
  
  acts_as_indexed :fields => [:order_number, :order_status, :address_line_1, :address_line_2, :city, :postal_code, :suburb]

  STATUSES = ['Awaiting EFT Payment', 'Awaiting Credit Card Payment', 'New', 'Processing', 'Complete', 'Cancelled', 'Stale']

  validates_inclusion_of :order_status, :in => STATUSES
  
  belongs_to :customer
  
  has_many :order_items
  
  # --- PRIVATE ---
  private

  def generate_reference_number
    self.order_number = "ORDER%04d" % id
    self.save
  end
  
  
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base

  

  validates_presence_of :order_id, :product_name, :price
  validates_numericality_of :price
  
  belongs_to :order
  
end

app/controllers/admin/order_items_controller.rb
module Admin
  class OrderItemsController < Admin::BaseController

    crudify :order_item,
            :title_attribute => 'product_name', :xhr_paging => true

  end
end

app/controllers/admin/orders_controller.rb
module Admin
  class OrdersController < Admin::BaseController

    crudify :order,
            :title_attribute => 'order_number', :xhr_paging => true

    def show
      @order = Order.find(params[:id])
    end
    
    def index
      if params[:order_status].present?
        @orders = Order.where(:order_status => params[:order_status]).paginate(:page => params[:page])
      else
        @orders = Order.paginate(:page => params[:page])
      end
    end
    
    def notification_recipients
      
      @recipients = RefinerySetting.find_or_set(:order_notification_recipients,
                                  ((Role[:refinery].users.first.email rescue nil) if defined?(Role)).to_s)
    
      if request.post?
        
        flash[:notice] = "The notification recipients have successfully been updated"
        unless request.xhr? or from_dialog?
          redirect_back_or_default(admin_orders_path)
        else
          render :text => "<script type='text/javascript'>parent.window.location = '#{admin_orders_path}';</script>",
                 :layout => false
        end
      end
    end
    
    def update_awaiting_eft
      update_status("Awaiting EFT Payment")
      
    end
    
    def update_awaiting_cc
      update_status("Awaiting Credit Card Payment")
      
    end
    
    def update_new  
      order = Order.find(params[:order_id])
          
      if params[:payment_type] == "Cash"
        OrderMailer.customer_cash_received(order.customer, order).deliver
      elsif params[:payment_type] == "Credit Card"
        OrderMailer.admin_credit_received(order.customer, order).deliver
      end
      
      update_status("New")
    end
    
    def update_processing
      update_status("Processing")
            
    end
    
    def update_complete
      update_status("Complete")
     
    end
    
    def update_cancelled
      update_status("Cancelled")
      
    end
    
    def update_stale
      update_status("Stale")
      
    end
    
    private
    
    def update_status(status)
      order = Order.find(params[:order_id])
      order.order_status = status
      order.save!
      
      redirect_to admin_order_path(order)
    end  
    
  end  
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  before_filter :find_all_order_items
  before_filter :find_page

  def index
    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @order_item in the line below:
    present(@page)
  end

  def show
    @order_item = OrderItem.find(params[:id])

    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @order_item in the line below:
    present(@page)
  end

protected

  def find_all_order_items
    @order_items = OrderItem.order('position ASC')
  end

  def find_page
    @page = Page.where(:link_url => "/order_items").first
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_filter :find_all_orders
  before_filter :find_page

  def index
    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @order in the line below:
    present(@page)
  end

  def show
    @order = Order.find(params[:id])

    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @order in the line below:
    present(@page)
  end

protected

  def find_all_orders
    @orders = Order.order('position ASC')
  end

  def find_page
    @page = Page.where(:link_url => "/orders").first
  end

end

app/views/admin/order_items/_actions.html.erb
<ul>
  <% if Admin::OrderItemsController.searchable? %>
    <li>
      <%= render :partial => "/shared/admin/search",
                  :locals => {
                    :url => admin_order_items_path
                  } %>
    </li>
  <% end %>
  <li>
    <%= link_to t('.create_new'), new_admin_order_item_path,
                 :class => "add_icon" %>
  </li>
<% if !searching? and Admin::OrderItemsController.sortable? and OrderItem.count > 1 %>
  <li>
    <%= link_to t('.reorder', :what => "Order Items"),
                 admin_order_items_path,
                 :id => "reorder_action",
                 :class => "reorder_icon" %>

    <%= link_to t('.reorder_done', :what => "Order Items"),
                 admin_order_items_path,
                 :id => "reorder_action_done",
                 :style => "display: none;",
                 :class => "reorder_icon" %>
  </li>
<% end %>
</ul>

app/views/admin/order_items/_form.html.erb
<%= form_for [:admin, @order_item] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
          :object => @order_item,
          :include_object_name => true
        } %>
  
  <div class='field'>
    <%= f.label :product_name -%>
    <%= f.text_field :product_name, :class => 'larger widest'  -%>
  </div>
  
  <div class='field'>
    <%= f.label :price -%>
    <%= f.text_field :price  -%>
  </div>
  
  <div class='field'>
    <%= f.label :order_id -%>
    <%= f.text_field :order_id  -%>
  </div>
  
  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('delete', :scope => 'admin.order_items.order_item'),
                :delete_confirmation => t('message', :scope => 'shared.admin.delete', :title => @order_item.product_name)
              } %>
<% end -%>

app/views/admin/order_items/_order_item.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(order_item) -%>">
  <span class='title'>
    <%= order_item.product_name %>
    <span class="preview">&nbsp;</span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag("application_go.png"), order_item_path(order_item),
        :title => t('.view_live_html'),
        :target => "_blank" %>
    <%= link_to refinery_icon_tag("application_edit.png"), edit_admin_order_item_path(order_item),
         :title => t('.edit') %>
    <%= link_to refinery_icon_tag("delete.png"), admin_order_item_path(order_item),
        :class => "cancel confirm-delete",
        :title => t('.delete'),
        :confirm => t('message', :scope => 'shared.admin.delete', :title => order_item.product_name),
        :method => :delete %>
  </span>
</li>

app/views/admin/order_items/_order_items.html.erb
<%= will_paginate @order_items %>
<%= render :partial => "sortable_list" %>

app/views/admin/order_items/_records.html.erb
<% if searching? %>
  <h2><%= t('results_for', :scope => 'shared.admin.search', :query => params[:search]) %></h2>
<% end %>
<% if @order_items.any? %>
  <div class='pagination_container'>
    <%= render :partial => 'order_items' %>
  </div>
<% else %>
  <p>
    <% unless searching? %>
      <strong>
        <%= t('.no_items_yet') %>
      </strong>
    <% else %>
      <%= t('no_results', :scope => 'shared.admin.search') %>
    <% end %>
  </p>
<% end %>

app/views/admin/order_items/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'order_item', :collection => @order_items %>
</ul>
<%= render :partial => "/shared/admin/sortable_list",
            :locals => {
              :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true
            } %>

app/views/admin/order_items/edit.html.erb
<%= render :partial => "form" %>

app/views/admin/order_items/index.html.erb
<section id='records'>
  <%= render :partial => 'records' %>
</section>
<aside id='actions'>
  <%= render :partial => 'actions' %>
</aside>
<%= render :partial => '/shared/admin/make_sortable',
            :locals => {
              :tree => false
            } if !searching? and Admin::OrderItemsController.sortable? and OrderItem.count > 1 %>

app/views/admin/order_items/new.html.erb
<%= render :partial => "form" %>

app/views/admin/orders/_actions.html.erb
<% if Admin::OrdersController.searchable? %>
  <ul class='search_list'>    	
    <li class='not_a_link'>
      <%= render :partial => "/shared/admin/search",
                  :locals => {
                    :url => admin_orders_path
                  } %>
    </li>
  </ul>
<% end %>

<ul class='collapsible_menu'>
  <li class='not_a_link'>
    <%= link_to 'View Orders', '#' %>
  </li>  
  <li id=<%= params[:order_status].present? ? "selected" : "" %>>
    <%= link_to "All", admin_orders_path %>
  </li>
  <li class=<%= params[:order_status] == "Awaiting EFT Payment" ? "selected" : "" %>>
    <%= link_to "Awaiting EFT Payment", admin_orders_path(:order_status => "Awaiting EFT Payment") %>
  </li>
  <li class=<%= params[:order_status] == "Awaiting Credit Card Payment" ? "selected" : "" %>>
    <%= link_to "Awaiting Credit Card Payment", admin_orders_path(:order_status => "Awaiting Credit Card Payment") %>
  </li>
  <li class=<%= params[:order_status] == "New" ? "selected" : "" %>>
    <%= link_to "New", admin_orders_path(:order_status => "New") %>
  </li>
  <li class=<%= params[:order_status] == "Processing" ? "selected" : "" %>>
    <%= link_to "Processing", admin_orders_path(:order_status => "Processing") %>
  </li>
  <li class=<%= params[:order_status] == "Complete" ? "selected" : "" %>>
    <%= link_to "Complete", admin_orders_path(:order_status => "Complete") %>
  </li> 
  <li class=<%= params[:order_status] == "Cancelled" ? "selected" : "" %>>
    <%= link_to "Cancelled", admin_orders_path(:order_status => "Cancelled") %>
  </li>
  <li class=<%= params[:order_status] == "Stale" ? "selected" : "" %>>
    <%= link_to "Stale", admin_orders_path(:order_status => "Stale") %>
  </li>
</ul>

<ul>
	<li>
      <%= link_to "Update who gets notified",
                  notification_recipients_admin_orders_path(:dialog => true, :height => 200),
                  :class => 'user_comment_icon' %>
    </li>
</ul>

app/views/admin/orders/_form.html.erb
<%= form_for [:admin, @order] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
          :object => @order,
          :include_object_name => true
        } %>
  
  <div class='field'>
    <%= f.label :order_number -%>
    <%= f.text_field :order_number, :class => 'larger widest'  -%>
  </div>
  
  <div class='field'>
    <%= f.label :customer -%>
    <%= f.text_field :customer  -%>
  </div>
  
  <div class='field'>
    <%= f.label :order_status -%>
    <%= f.text_field :order_status  -%>
  </div>
  
  <div class='field'>
    <%= f.label :grand_total -%>
    <%= f.text_field :grand_total  -%>
  </div>
  
  <div class='field'>
    <%= f.label :address_line_1 -%>
    <%= f.text_field :address_line_1  -%>
  </div>
  
  <div class='field'>
    <%= f.label :address_line_2 -%>
    <%= f.text_field :address_line_2  -%>
  </div>
  
  <div class='field'>
    <%= f.label :city -%>
    <%= f.text_field :city  -%>
  </div>
  
  <div class='field'>
    <%= f.label :postal_code -%>
    <%= f.text_field :postal_code  -%>
  </div>
  
  <div class='field'>
    <%= f.label :suburb -%>
    <%= f.text_field :suburb  -%>
  </div>
  
  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('delete', :scope => 'admin.orders.order'),
                :delete_confirmation => t('message', :scope => 'shared.admin.delete', :title => @order.order_number)
              } %>
<% end -%>

app/views/admin/orders/_order.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(order) -%>">
  <span class='title'>
    <%= order.order_number %>
    <span class="preview">&nbsp;</span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag("application_go.png"), order_path(order),
        :title => 'View Live Html',
        :target => "_blank" %>
    <%= link_to refinery_icon_tag("application_edit.png"), admin_order_path(order),
        :title => 'Edit' %>
    <%= link_to refinery_icon_tag("delete.png"), admin_order_path(order),
        :class => "cancel confirm-delete",
        :title => 'Delete',
        :confirm => t('message', :scope => 'shared.admin.delete', :title => order.order_number),
        :method => :delete %>
  </span>
</li>

app/views/admin/orders/_orders.html.erb
<%= will_paginate @orders %>
<%= render :partial => "sortable_list" %>

app/views/admin/orders/_records.html.erb
<% if searching? %>
  <h2><%= t('results_for', :scope => 'shared.admin.search', :query => params[:search]) %></h2>
<% end %>
<% if @orders.any? %>
  <div class='pagination_container'>
    <%= render :partial => 'orders' %>
  </div>
<% else %>
  <p>
    <% unless searching? %>
      <strong>
        <%= t('.no_items_yet') %>
      </strong>
    <% else %>
      <%= t('no_results', :scope => 'shared.admin.search') %>
    <% end %>
  </p>
<% end %>

app/views/admin/orders/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'order', :collection => @orders %>
</ul>
<%= render :partial => "/shared/admin/sortable_list",
            :locals => {
              :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true
            } %>

app/views/admin/orders/edit.html.erb
<%= render :partial => "form" %>

app/views/admin/orders/index.html.erb
<section id='records'>
  <%= render :partial => 'records' %>
</section>
<nav id='actions' class='multilist'>
  <%= render :partial => 'actions' %>
</nav>
<%= render :partial => '/shared/admin/make_sortable',
            :locals => {
              :tree => false
            } if !searching? and Admin::OrdersController.sortable? and Order.count > 1 %>

app/views/admin/orders/new.html.erb
<%= render :partial => "form" %>

app/views/admin/orders/notification_recipients.html.erb
<%= form_tag do %>

  <div class='field'>
    <span class='label_with_help'>
      <%= label_tag :recipients %>
    </span>
    <%= text_field_tag :recipients, @recipients, :class => "larger widest" %>
  </div>
  
  <%= render :partial => "/shared/admin/form_actions",
             :locals => {
               :f => nil,
               :continue_editing => false,
               :cancel_url => admin_orders_url,
               :hide_delete => true
             } %>
<% end %>

app/views/admin/orders/show.html.erb
<%= form_for [:admin, @order] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
          :object => @order,
          :include_object_name => true
        } %>
  
  <div class="content">

	  <div class='field'>    
	    <h2>Order Number: <%= @order.order_number  -%></h2>
	  </div>
	
	  <div class='customer_details'>
		  <div class='label'>
			  <div class='field'>
			    <b>Order Status:</b>
			  </div>
			  <div class='field'>
			    <b>Payment Type:</b>
			  </div>
		  </div>
		  <div class='text'>
			  <div class='field'>
			    <%= @order.order_status  -%>
			  </div>
			  <div class='field'>
			    <%= @order.payment_type  -%>
			  </div>
		  </div>
	  </div>	

	  <div class="address">
		  <div class='second_label'>
			  <div class='field'>
			    <b>Date:</b>
			  </div>
		  </div>
		  <div class='text'>
			  <div class='field'>
			    <%= @order.created_at.strftime("%d %B %Y") -%>
			  </div>
		  </div>		  	
	  </div>

	  <br><br>
	  <div class='field'>
	  	<h2>Customer Details</h2>
	  </div>

	  <div class="customer_details">
	
		  <div class='label'>
			<div class='field'>	
		    	<b>Name: </b>
			</div>		  
			<div class='field'>
				<b>Surname: </b>
			</div>		  
			<div class='field'>
				<b>Contact No: </b>
			</div>
		  </div>
		  <div class='text'>
			<div class='field'>
				<%= link_to @order.customer.name, admin_customer_path(@order.customer)  -%>
			</div>
			<div class='field'>
				<%= @order.customer.surname  -%>
			</div>
			<div class='field'>
				<%= @order.customer.contact_number  -%>
			</div>
		  </div>
	  </div>
	  
	  <div class="address">
		  <div class='second_label'>
		    <b>Address: </b>
		  </div>
		  <div class='text'>
			<div class='field'>
		    	<%= @order.address_line_1  -%>
			</div>
			<div class='field'>  
		    	<%= @order.address_line_2  -%>
			</div>
			<div class='field'>		  	    
		    	<%= @order.suburb  -%>
			</div>
			<div class='field'>		  
		    	<%= @order.city  -%>
			</div>
			<div class='field'>		  
		    	<%= @order.postal_code  -%>
			</div>
		  </div>
	  </div>
	  <div class="clear"></div>
	  <br><BR>
	  <div class='field'>
	  	<h2>Order Details</h2>
	  </div>
	  <hr />
	  
	
	  <table width="100%">
		  <tr class="<%= cycle("even", "odd") %>"> 
			<th><b>Product Name</b></th>
			<th><b>Price</b></th>
			<th><b>Quantity</b></th>
			<th><b>Stock Code</b></th>
			<th><b>Total Price</b></th>
		  </tr>
		  <% @order.order_items.each do |order_item| %>
				<tr class="<%= cycle("odd", "even") %>"> 
					<td style="border:1 solid grey;"><%= order_item.product_name  -%></td>
					<td style="border:1 solid grey;"><%= rands(order_item.price)  -%></td>
					<td style="border:1 solid grey;"><%= order_item.quantity  -%></td>
					<td style="border:1 solid grey;"><%= order_item.stock_code  -%></td>
					<td style="border:1 solid grey;"><%= rands(order_item.total)  -%></td>
				</tr>
	  	  <% end %>
		  <tr class="<%= cycle("odd", "even") %>">
				<td colspan="4"><b>Grand Total</b></td>
				<td><%= rands(@order.grand_total)  -%></td>
		  </tr>
	  </table>

  </div>

  <div class="statuses">
	<% if @order.order_status.present? %>
	<h2>Update Status</h2>

		<% if @order.order_status == 'Awaiting EFT Payment' %>
			<%= link_to 'Payment Received', admin_order_update_new_path(:order_id => @order.id, :payment_type => @order.payment_type), :class => "status" %>	
			<%= link_to 'Cancelled', admin_order_update_cancelled_path(:order_id => @order.id), :class => "status" %>
		 	<%= link_to 'Stale', admin_order_update_stale_path(:order_id => @order.id), :class => "status" %>
		<% elsif @order.order_status == 'Awaiting Credit Card Payment' %>
			<!-- temporary measure to simulate payment successful from payment gateway -->
				<%= link_to 'Payment Received', admin_order_update_new_path(:order_id => @order.id, :payment_type => @order.payment_type), :class => "status" %>
			<!-- --------------------------------------------------------------------- -->
		 	<%= link_to 'Stale', admin_order_update_stale_path(:order_id => @order.id), :class => "status" %>
		<% elsif @order.order_status == 'New' %>
			<%= link_to 'Processing', admin_order_update_processing_path(:order_id => @order.id), :class => "status" %>
			<%= link_to 'Cancelled', admin_order_update_cancelled_path(:order_id => @order.id), :class => "status" %>
		<% elsif @order.order_status == 'Processing' %>
			<%= link_to 'Complete', admin_order_update_complete_path(:order_id => @order.id), :class => "status" %>
			<%= link_to 'Cancelled', admin_order_update_cancelled_path(:order_id => @order.id), :class => "status" %>
		<% end %>

	<!-- 
	<%#= link_to 'Awaiting EFT Payment', admin_order_update_awaiting_eft_path(:order_id => @order.id), :class => "status" %>
	<%#= link_to 'Awaiting Credit Card Payment', admin_order_update_awaiting_cc_path(:order_id => @order.id), :class => "status" %>
	 -->

  	<% end %>
  </div>
 
  <div class="clear"></div>
<% end -%>

app/views/order_items/index.html.erb
<% content_for :body_content_left do %>
  <ul id="order_items">
    <% @order_items.each do |order_item| %>
      <li>
        <%= link_to order_item.product_name, order_item_path(order_item) %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= render :partial => "/shared/content_page" %>

app/views/order_items/show.html.erb
<% content_for :body_content_title do %>
  <%= @order_item.product_name %>
<% end %>

<% content_for :body_content_left do %>
  <section>
    <h1>Product Name</h1>
    <p>
      <%=raw @order_item.product_name %>
    </p>
  </section>
  <section>
    <h1>Price</h1>
    <p>
      <%=raw @order_item.price %>
    </p>
  </section>
  <section>
    <h1>Order</h1>
    <p>
      <%=raw @order_item.order_id %>
    </p>
  </section>
<% end %>

<% content_for :body_content_right do %>
  <aside>
    <h2><%= t('.other') %></h2>
    <ul id="order_items">
      <% @order_items.each do |order_item| %>
        <li>
          <%= link_to order_item.product_name, order_item_path(order_item) %>
        </li>
      <% end %>
    </ul>
  </aside>
<% end %>

<%= render :partial => "/shared/content_page" %>

app/views/orders/index.html.erb
<% content_for :body_content_left do %>
  <ul id="orders">
    <% @orders.each do |order| %>
      <li>
        <%= link_to order.order_number, order_path(order) %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= render :partial => "/shared/content_page" %>

app/views/orders/show.html.erb
<% content_for :body_content_title do %>
  <%= @order.order_number %>
<% end %>

<% content_for :body_content_left do %>
  <section>
    <h1>Order Number</h1>
    <p>
      <%=raw @order.order_number %>
    </p>
  </section>
  <section>
    <h1>Customer</h1>
    <p>
      <%=raw @order.customer %>
    </p>
  </section>
  <section>
    <h1>Order Status</h1>
    <p>
      <%=raw @order.order_status %>
    </p>
  </section>
  <section>
    <h1>Grand Total</h1>
    <p>
      <%=raw @order.grand_total %>
    </p>
  </section>
  <section>
    <h1>Address Line 1</h1>
    <p>
      <%=raw @order.address_line_1 %>
    </p>
  </section>
  <section>
    <h1>Address Line 2</h1>
    <p>
      <%=raw @order.address_line_2 %>
    </p>
  </section>
  <section>
    <h1>City</h1>
    <p>
      <%=raw @order.city %>
    </p>
  </section>
  <section>
    <h1>Postal Code</h1>
    <p>
      <%=raw @order.postal_code %>
    </p>
  </section>
  <section>
    <h1>Suburb</h1>
    <p>
      <%=raw @order.suburb %>
    </p>
  </section>
<% end %>

<% content_for :body_content_right do %>
  <aside>
    <h2><%= t('.other') %></h2>
    <ul id="orders">
      <% @orders.each do |order| %>
        <li>
          <%= link_to order.order_number, order_path(order) %>
        </li>
      <% end %>
    </ul>
  </aside>
<% end %>

<%= render :partial => "/shared/content_page" %>